### PR TITLE
Unions for base types

### LINKED ISSUE #77: Should vectors extend common vector type?
So that (e.g.) you could define a method that worked on all vectors.

### LINKED ISSUE #94: Integer should inherit from numeric?
``` r
library(R7)

foo <- new_generic("foo", "x")
method(foo, "numeric") <- function(x, ...) {
  10
}
foo(1:10)
#> Error: Can't find method for generic `foo()` with classes:
#> - x: <integer>
```

<sup>Created on 2021-10-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by hadley**
* Adds numeric, atomic, and vector unions
* Adds expression base type

Fixes #77. Fixes #94.

### CODE REVIEW

**Comment by hadley** [comment]
@davisvaughan can you take a look at this PR too? The goal is to treat "numeric", "atomic", and "vector" like unions; i.e. you can't extend from them, but you can dispatch and use in properties.

File: R/zzz.R [hunk 1]
```diff
@@ -72,6 +73,20 @@ R7_union <- new_class(
...
 
+#' @export
+str.R7_union <- function(object, ..., nest.lev = 0) {
+  cat(if (nest.lev > 0) " ")
+  cat("<R7_union>: ", class_desc(object), sep = "")
+  cat("\n")
+
+  if (nest.lev == 0) {
+    props <- props(object)
+    props$srcref <- NULL
```
Comment (DavisVaughan) [inline R/zzz.R:84]: Where does this come from?

File: R/zzz.R [hunk 2]
```diff
@@ -107,3 +122,10 @@ global_variables(c("name", "parent", "properties", "constructor", "validator"))
   env <- as.environment(paste0("package:", pkgname))
   env[[".conflicts.OK"]] <- TRUE
 }
+
+.onLoad <- function(...) {
+  base_classes$`NULL` <- new_base_class("NULL")
```
Comment (DavisVaughan) [inline R/zzz.R:127]:
```suggestion
  base_classes$`NULL` <<- new_base_class("NULL")
```

? just guessing based on the others

File: src/dispatch.c [hunk 3]
```diff
@@ -51,7 +51,7 @@ SEXP method_internal(SEXP table, SEXP signature, R_xlen_t signature_itr, SEXP ig
 SEXP get_class(SEXP object, SEXP envir) {
     static SEXP fun = NULL;
     if (fun == NULL) {
-      fun = Rf_findVarInFrame(R_BaseEnv, Rf_install("class"));
+      fun = Rf_findVarInFrame(R_BaseEnv, Rf_install(".class2"));
```
Comment (DavisVaughan) [inline src/dispatch.c:54]: This is kind of nice for matrices/arrays too, even though I think we haven't fully thought about those yet

> .class2(matrix(1))
[1] "matrix"  "array"   "double"  "numeric"
> class(matrix(1))
[1] "matrix" "array"

**Review by DavisVaughan — APPROVED** [review]
Looks nice!

File: src/dispatch.c (hunk 3 above)
Comment (hadley) [reply src/dispatch.c:54]: Yeah, we could always back port, if needed.

File: R/zzz.R (hunk 1 above)
Comment (hadley) [reply R/zzz.R:84]: No idea; and it's not needed. I'll remove.

File: tests/testthat/helper.R [hunk 4]
```diff
@@ -1,5 +1,5 @@
 text <- new_class("text", parent = "character", constructor = function(text = character()) new_object(.data = text))
-number <- new_class("number", parent = "numeric", constructor = function(x) new_object(.data = x))
+number <- new_class("number", parent = "double", constructor = function(x) new_object(.data = x))
```
[the remark this answers is not in the document]
Comment (hadley) [reply tests/testthat/helper.R:2]: Yeah, `parent` can't be a union because it has to be a concrete type. There's already a test for it.

File: tests/testthat/test-class.R [hunk 5]
```diff
@@ -33,18 +33,14 @@ describe("R7_class", {
 })
 
 test_that("classes can inherit from base types", {
-  types <- c("logical", "integer", "complex", "character", "raw", "list")
+  types <- c("logical", "integer", "double", "complex", "character", "raw", "list")
```
[the remark this answers is not in the document]
Comment (hadley) [reply tests/testthat/test-class.R:36]: I'll do that in a separate PR since it's unrelated to this one.

File: tests/testthat/test-class.R [hunk 6]
```diff
@@ -33,18 +33,14 @@ describe("R7_class", {
...
   for (type in types) {
     f <- match.fun(type)
     foo <- new_class("foo", parent = type, constructor = function(x = f()) new_object(x))
     obj <- foo()
     expect_equal(typeof(r7_data(obj)), type)
   }
 
-  foo <- new_class("foo", parent = "numeric", constructor = function(x = numeric()) new_object(x))
-  obj <- foo()
-  expect_equal(typeof(r7_data(obj)), "double")
```
[the remark this answers is not in the document]
Comment (hadley) [reply tests/testthat/test-class.R:46]: See the next test 😉
