### PR TITLE
Fully define constructor

### LINKED ISSUE #102: Can't construct object with class hierarchy
``` r
library(R7)
foo <- new_class("foo", properties = list("x" = "numeric"))
foo2 <- new_class("foo2", foo, properties = list("y" = "numeric"))
foo2(x = 1, y = 2)
#> Error in do.call(base::`@`, list(object, name)): trying to get slot "parent" from an object of a basic class ("character") with no slots
```

<sup>Created on 2021-10-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I feel like I'm missing something obvious here, so this might just need a better error.

### LINKED ISSUE #103: Ensure that object fully initialised
```R
library(R7)
foo <- new_class("foo", properties = list("x" = "numeric"))
f <- foo()
f@x
#> Error: Can't find property <foo>@x
```

And maybe define a default value in `new_property()`?

### PR DESCRIPTION
**Pull request by hadley**
The default constructor gets one argument for each property, passing on to the parent as appropriate.

Fixes #102. Fixes #103.

### CODE REVIEW

File: R/zzz.R [hunk 1]
```diff
@@ -10,19 +10,23 @@ R7_object <- new_class(
   }
 )
 
+new_base_class <- function(name) {
+  R7_class(name = name, constructor = function(.data) new_object(.data))
```
Comment (hadley) [inline R/zzz.R:14]: I think the constructor argument has to be called `.data` (since that's what the property is) and they shouldn't have a default for consistency with the other R7 objects.

**Comment by hadley** [comment]
@jimhester this probably needs more tests, but it would be good to get a second pair of eyes on it before I go much further. I'd suggest starting with https://github.com/RConsortium/OOP-WG/pull/112/files#diff-e1ddedf6c866fcae78a08c0656dd95f6da48dbd33c398917b9fd724685bd1e6d

File: tests/testthat/_snaps/object.md [hunk 2]
```diff
@@ -4,19 +4,19 @@
       foo <- new_class("foo")
       foo(1)
     Error <simpleError>
-      All arguments to <foo> constructor must be named
+      unused argument (1)
```
Comment (jimhester) [inline tests/testthat/_snaps/object.md:7]: Are ok with these error messages now being less informative?

I think so since the constructor now has the properties as full arguments, but wanted to double check

**Review by jimhester — APPROVED** [review]

File: tests/testthat/_snaps/object.md (hunk 2 above)
Comment (hadley) [reply tests/testthat/_snaps/object.md:7]: Yeah, it's a bit of a bummer (especially since I just wrote this code 😆), but I think it's a net win.
